[[erlang_library]]
deps = [
  "//3rdparty/rebar3/default/lib/observer_cli",
  "//apps/emqx/_build/default/lib/recon/src",
  "//apps/emqx/src",
  "//apps/emqx_conf/src",
  "//apps/emqx_exhook/src",
  "//apps/emqx_management/src",
  "//apps/emqx_modules/src/proto",
  "//apps/emqx_plugins/src"
]
name = "src"


