[[erlang_library]]
deps = [
  "//apps/emqx/_build/default/lib/ekka/src",
  "//apps/emqx/_build/default/lib/esockd/src",
  "//apps/emqx/_build/default/lib/hocon/src",
  "//apps/emqx/_build/default/lib/mria/src",
  "//apps/emqx/src",
  "//apps/emqx_authn/src",
  "//apps/emqx_conf/src",
  "//apps/emqx_dashboard/src",
  "//apps/emqx_gateway/src/proto",
  "//apps/emqx_management/src",
  "//apps/emqx_rule_engine/src"
]
name = "src"


