[[erlang_library]]
deps = [
  "//apps/emqx/_build/default/lib/hocon/src",
  "//apps/emqx/src",
  "//apps/emqx_authn/src/proto",
  "//apps/emqx_conf/src",
  "//apps/emqx_plugin_libs/src",
  "//apps/emqx_resource/src"
]
name = "src"


