[[erlang_library]]
deps = [
  "//3rdparty/rebar3/default/lib/eldap2",
  "//3rdparty/rebar3/default/lib/epgsql",
  "//3rdparty/rebar3/default/lib/eredis",
  "//3rdparty/rebar3/default/lib/eredis_cluster",
  "//3rdparty/rebar3/default/lib/mongo_api",
  "//3rdparty/rebar3/default/lib/mysql",
  "//apps/emqx/_build/default/lib/hocon/src",
  "//apps/emqx/src",
  "//apps/emqx_bridge/src",
  "//apps/emqx_conf/src",
  "//apps/emqx_connector/src/mqtt",
  "//apps/emqx_dashboard/src",
  "//apps/emqx_plugin_libs/src"
]
name = "src"


